djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v

urlpatterns = [
    path('admin', admin.site.urls),
    path('register/', v.register, name="register"),
    path('', include("invitations.urls")),
    path('', include('django.contrib.auth.urls')),
]

invitations/urls.py
from django.urls import path
from . import views

urlpatterns = [path(f"", views.index, name="index"),
               path(f"home/", views.home, name="home"),
               path(f"", views.home, name="home"),
               path(f"groups/", views.groups, name="groups"),
               path(f"groups/add", views.create_groups, name="create_groups"),
               path(f"events/", views.events, name="events"),
               path(f"templates/", views.templates, name="templates"),
               path(f"guests/", views.guests, name="guests"),
               path(f"events/add/", views.add_event, name="add_event"),
               path(f"events/change/<int:event_id>", views.change_event, name="change_event"),
               path(f"events/delete/", views.delete_event, name="delete_event"),
               path(f"groups/delete/", views.delete_group, name="delete_group"),
               path(f"guests/add/", views.add_guest, name="add_guest"),
               path(f"guests/change/<int:guest_id>", views.change_guest, name="change_guest"),
               path(f"guests/delete/", views.delete_guest, name="delete_guest"),
               path(f"templates/add/", views.add_template, name="add_template"),
               path(f"templates/change/<int:template_id>", views.change_template, name="change_template"),
               path(f"templates/delete/", views.delete_template, name="delete_template"),
               path(f"events/render/<int:event_id>", views.render_event, name="render_event"),
               path(f"groups/view_group/<int:group_id>", views.view_group, name="view_group"),

               ]

invitations/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from datetime import date


class Group(models.Model):
    name = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="group", null=True)

    def __str__(self):
        return self.name


class Guest(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    parent_name = models.CharField(max_length=200, default='Unknown')
    parent_phone = models.CharField(max_length=200, default='Unknown')
    email = models.EmailField(help_text="jaan@mail.com", default='Unknown')
    phone = models.CharField(max_length=200, default='Unknown')
    address = models.CharField(max_length=200, default='Unknown')

    def __str__(self):
        return self.first_name


class Template(models.Model):
    name = models.CharField(max_length=200)
    content = models.TextField(max_length=500)
    template_file = models.TextField(max_length=500)
    example_img = models.TextField(max_length=500)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="template", null=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    template = models.ForeignKey(Template, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    host = models.CharField(max_length=100)
    date = models.DateField(default=date.today())
    start = models.TimeField(default=datetime.time(16, 00))
    finish = models.TimeField(default=datetime.time(16, 00))
    place = models.CharField(max_length=200)
    contact_number = models.CharField(max_length=100)
    contact_person = models.CharField(max_length=100)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="event", null=True)

    def __str__(self):
        return self.name

invitations/forms.py
import django.forms.widgets
from django import forms
from django.forms import NumberInput, DateInput, TimeInput

from .models import Group, Template, Guest, Event


def get_tuples_groups():
    return tuple([(group.id, group.name) for group in Group.objects.all()])


class NewGroupForm(forms.Form):
    name = forms.CharField(label="Name", max_length=200)


def get_tuples_templates():
    return tuple([(template.id, template.name) for template in Template.objects.all()])


class AddEventForm(forms.ModelForm):

    def __init__(self, *args, groups, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        self.fields['group'].choices = sorted(groups, key=lambda t: t[1])

    group = forms.ChoiceField(choices=(), required=True)

    class Meta:
        model = Event
        fields = ['template', 'name', 'host', 'date', 'start', 'finish', 'place', 'contact_number',
                  'contact_person']
        widgets = {'date': DateInput(attrs={'type': 'date'}),
                   'start': TimeInput(attrs={'type': 'time'}),
                   'finish': TimeInput(attrs={'type': 'time'}),
                   'user': forms.HiddenInput()}


class DeleteForm(forms.Form):
    id = forms.IntegerField(label="id")


class AddGuestForm(forms.ModelForm):
    class Meta:
        model = Guest
        fields = ['first_name', 'last_name', 'parent_name', 'parent_phone', 'email', 'phone', 'address']

    def __init__(self, *args, groups, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        self.fields['group'].choices = sorted(groups, key=lambda t: t[1])
        self.fields['last_name'].required = False
        self.fields['parent_name'].required = False
        self.fields['parent_phone'].required = False
        self.fields['email'].required = False
        self.fields['phone'].required = False
        self.fields['address'].required = False

    group = forms.ChoiceField(choices=(), required=True)


class AddTemplateForm(forms.ModelForm):
    class Meta:
        model = Template
        fields = ['name', 'content']

invitations/controllers.py
from models import *


class ControllerEvent:
    pass


class ControllerGuest:
    pass


class ControllerGroup:
    @staticmethod
    def get_all_groups_by_user(user):
        return user.group.all()


class ControllerTemplate:
    pass

invitations/views.py
import datetime

from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, redirect

from .forms import NewGroupForm, AddEventForm, DeleteForm, AddGuestForm, AddTemplateForm
from .models import Group, Guest, Event, Template


def index(request):
    return render(request, "invitations/home.html")


def home(request):
    return render(request, "invitations/home.html")


def groups(request):
    try:
        user = request.user
        groups_ = user.group.all()
        return render(request, "invitations/groups.html", {"groups": groups_})
    except Exception as e:
        messages.error(request, f'{e}')
        return redirect('/home/')


def create_groups(request):
    try:
        user = request.user
        try:
            if request.method == "POST":
                form = NewGroupForm(request.POST)

                if form.is_valid():
                    n = form.cleaned_data["name"]
                    g = Group(name=n)
                    g.user = user
                    g.save()
                    groups_ = user.group.all()
                    messages.success(request, "Group was created successfully!")
                    return render(request, "invitations/groups.html", {"groups": groups_})
            else:
                groups_ = user.group.all()
                return render(request, "invitations/create_groups.html", {"groups": groups_})
        except Exception as e:
            messages.error(request, f'{e}')
            groups_ = user.group.all()
            return render(request, "invitations/groups.html", {"groups": groups_})
    except Exception as e:
        messages.error(request, f'{e}')
        return redirect('/home/')


def delete_group(request):
    user = request.user
    if request.method == "POST":
        form = DeleteForm(request.POST)
        try:
            if form.is_valid():
                group_id = form.cleaned_data["id"]
                try:
                    group = Group.objects.get(id=group_id)
                    if group:
                        group.delete()
                        messages.success(request, "Group was deleted successfully!")
                        groups_ = user.group.all()
                        return render(request, "invitations/groups.html", {"groups": groups_})
                except Exception as e:
                    groups_ = user.group.all()
                    messages.error(request, f'{e}')
                    return render(request, "invitations/groups.html", {"groups": groups_})
            else:
                groups_ = user.group.all()
                return render(request, "invitations/groups.html", {"groups": groups_})
        except Group.DoesNotExist:
            messages.error(request, 'Wrong group id')
            return redirect('/group/')


def events(request):
    try:
        user = request.user
        events_ = user.event.all()
        return render(request, "invitations/events.html", {"events": events_})
    except Exception as e:
        messages.error(request, f'{e}')
        return redirect('/home/')


def add_event(request):
    try:
        user = request.user
        if request.method == "POST":
            user_group_all = list(map(lambda group_: (group_.id, group_.name), user.group.all()))
            form = AddEventForm(request.POST, groups=user_group_all)

            if form.is_valid():
                n = form.cleaned_data["name"]
                group = user.group.all().get(id=int(form.cleaned_data["group"]))
                t = form.cleaned_data["template"]
                h = form.cleaned_data["host"]
                d = str(form.cleaned_data["date"])
                st = str(form.cleaned_data["start"])
                fin = str(form.cleaned_data["finish"])
                pl = form.cleaned_data["place"]
                cn = form.cleaned_data["contact_number"]
                cp = form.cleaned_data["contact_person"]
                e = Event(name=n, group=group, template_id=t.id, host=h, place=pl,
                          contact_number=cn, contact_person=cp, date=d, start=st, finish=fin, user=user)
                e.save()
                messages.success(request, "Event was created successfully!")
                events_ = user.event.all()
                return render(request, "invitations/events.html", {"events": events_})
            else:
                return render(request, "invitations/add_event.html", {"form": form})

        else:
            user_group_all = list(map(lambda group: (group.id, group.name), user.group.all()))
            form = AddEventForm(request.POST, groups=user_group_all)
            form.is_valid()
            return render(request, "invitations/add_event.html", {"form": form})
    except Exception as e:
        messages.error(request, f"{e}")
        return redirect('/home/')


def change_event(request, event_id):
    try:
        user = request.user
        try:
            event = user.event.select_for_update().get(id=event_id)

            if request.method == "POST":
                user_group_all = list(map(lambda group_: (group_.id, group_.name), user.group.all()))
                form = AddEventForm(request.POST, groups=user_group_all)

                if form.is_valid():
                    event.name = form.instance.name
                    event.group = user.group.get(id=int(form.cleaned_data['group']))
                    event.template = form.instance.template
                    event.host = form.instance.host
                    event.date = form.instance.date
                    event.start = form.instance.start
                    event.finish = form.instance.finish
                    event.place = form.instance.place
                    event.contact_number = form.instance.contact_number
                    event.contact_person = form.instance.contact_person
                    event.save()
                    messages.success(request, "Event was changed successfully!")
                    return redirect("/events/")
                else:
                    return render(request, "invitations/change_event.html", {"form": form})

            else:
                user_group_all = list(map(lambda group: (group.id, group.name), user.group.all()))
                form = AddEventForm(instance=event, groups=user_group_all, initial={'group': str(event.group_id)})
                return render(request, "invitations/change_event.html", {"form": form})
        except Event.DoesNotExist:
            raise Http404("No group matches the given query.")
    except Exception as e:
        messages.error(request, f'{e}')
        return redirect('/home/')


def delete_event(request):
    try:
        user = request.user
        if request.method == "POST":
            form = DeleteForm(request.POST)
            if form.is_valid():
                event_id = form.cleaned_data["id"]
                try:
                    event = Event.objects.get(id=event_id)
                    if event:
                        event.delete()
                        events_ = user.event.all()
                        return render(request, "invitations/events.html", {"events": events_})
                except Exception as e:
                    events_ = user.event.all()
                    return render(request, "invitations/events.html", {"events": events_})
            else:
                events_ = user.event.all()
                return render(request, "invitations/events.html", {"events": events_})
    except Exception as e:
        messages.error(request, f'{e}')
        return redirect('/home/')


def templates(request):
    try:
        templates_ = Template.objects.all()
        return render(request, "invitations/templates.html", {"templates": templates_})
    except Exception as e:
        messages.error(request, f'{e}')
        return redirect('/home/')


def guests(request):
    try:
        user = request.user
        groups_ = user.group.all()
        return render(request, "invitations/guests.html", {"groups": groups_})
    except Exception as e:
        messages.error(request, f'{e}')
        return redirect('/home/')


def add_guest(request):
    user = request.user
    try:
        if request.method == "POST":
            user_group_all = list(map(lambda group_: (group_.id, group_.name), user.group.all()))
            form = AddGuestForm(request.POST, groups=user_group_all)
            if form.is_valid():
                n = form.cleaned_data["first_name"]
                g = user.group.get(id=int(form.cleaned_data['group']))
                ln = form.cleaned_data["last_name"]
                pn = form.cleaned_data["parent_name"]
                p_ph = form.cleaned_data["parent_phone"]
                email = form.cleaned_data["email"]
                phone = form.cleaned_data["phone"]
                address = form.cleaned_data["address"]

                guest = Guest(first_name=n, group=g, last_name=ln, parent_name=pn, parent_phone=p_ph,
                              email=email, phone=phone, address=address)
                guest.save()
                messages.success(request, "Guest was added successfully!")
                groups_ = user.group.all()
                return render(request, "invitations/guests.html", {"groups": groups_})
        else:
            user_group_all = list(map(lambda group: (group.id, group.name), user.group.all()))
            form = AddGuestForm(request.POST, groups=user_group_all)
            return render(request, "invitations/add_guest.html", {"form": form})
    except Exception as e:
        messages.error(request, f'{e}')


def change_guest(request, guest_id):
    user = request.user
    try:
        if request.method == "POST":
            user_group_all = list(map(lambda group_: (group_.id, group_.name), user.group.all()))
            form = AddGuestForm(request.POST, groups=user_group_all)
            form.is_valid()

templates/invitations/add_event.html
{% extends 'invitations/home.html' %}

{% block title %}<title>Adding a new event</title>{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Adding a new event</h1>
    <form method="POST" action="/events/add/" class="form-group">
    {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
    {{ form|crispy }}</div>
    <button type="submit" name="save" class="btn btn-success"> Add </button>
            </div>
    </form>
{% endblock %}

templates/invitations/add_guest.html
{% extends 'invitations/home.html' %}

{% block title %}<title>Adding a new guest</title>{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Adding a new guest</h1>
    <form method="POST" action="" class="form-group">
    {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
    {{ form|crispy }}</div>
    <button type="submit" name="save" class="btn btn-success"> Add </button>
            </div>
    </form>
{% endblock %}

templates/invitations/add_template.html
{% extends 'invitations/home.html' %}

{% block title %}<title>Adding a new template</title>{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Adding a new template</h1>
    <form method="POST" action="" class="form-group">
    {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
    {{ form|crispy }}</div>
    <button type="submit" name="save" class="btn btn-success"> Add </button>
            </div>
    </form>
{% endblock %}

templates/invitations/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
        .sidenav {
            height: 100%;
            width: 160px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            padding-top: 20px;
        }

        .sidenav a {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
        }

        .sidenav a:hover {
            color: #f1f1f1;
        }

        .main {
            margin-left: 160px;
            padding: 0px 10px;
        }

    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% block title %} <title>Invitations</title>{% endblock %}

</head>
<body>


<div class="row justify-content-center">
    <div class="col-8">
        <h1 class="mt-2">Invitations</h1>
        <hr class="mt-0 mb-4">

        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <strong>Hey!</strong> {{ message }}
                </div>
            {% endif %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                  <strong>Hey!</strong> {{ message }}
                </div>
            {% endif %}

        {% endfor %}


        {% if user.is_authenticated %}
            <style>
                .sidenav {
                    height: 100%;
                    width: 160px;
                    position: fixed;
                    z-index: 1;
                    top: 0;
                    left: 0;
                    background-color: #111;
                    overflow-x: hidden;
                    padding-top: 20px;
                }

                .sidenav a {
                    padding: 6px 8px 6px 16px;
                    text-decoration: none;
                    font-size: 25px;
                    color: #818181;
                    display: block;
                }

                .sidenav a:hover {
                    color: #f1f1f1;
                }

                .main {
                    margin-left: 160px;
                    padding: 0px 10px;

                }

                html {
                    overflow-y: scroll;
                }

            </style>

            <div class="sidenav">
                <a href="/home">Home</a>
                <a href="/events">Events</a>
                <a href="/templates">Templates</a>
                <a href="/guests">Guests</a>
                <a href="/groups">Groups</a>
                <a href="/logout">Log out</a>

            </div>

            <div class="row justify-content-center">
                {% block content %}
                {% endblock %}


            </div>

        {% else %}

            <div id="content" class="list-group w-auto">
                <div class="list-group-item list-group-item-action d-flex gap-3 py-3">Log in <a href="/login"> here.</a></div>
                <div class="list-group-item list-group-item-action d-flex gap-3 py-3">Register <a href="/register"> here.</a></div>

            </div>

        {% endif %}
        <p class="mt-5 mb-3 text-muted card-footer">&copy Alina 2022 </p>
    </div>

</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>

</body>
</html>

templates/invitations/change_event.html
{% extends 'invitations/home.html' %}

{% block title %}<title>Change an event</title>{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Change an event</h1>
    <form method="POST" action="/events/change/{{ form.instance.id }}" class="form-group">
    {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
    {{ form|crispy }}</div>
    <button type="submit" name="save" class="btn btn-success"> Save changes </button>
            </div>
    </form>
{% endblock %}

templates/invitations/change_guest.html
{% extends 'invitations/home.html' %}

{% block title %}<title>Change a guest </title>{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST" action="/guests/change/{{ form.instance.id }}" class="form-group">
        {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                {{form.as_p}}
            </div>
            <button type="submit" name="save" class="btn btn-success"> Save changes</button>
        </div>
    </form>
{% endblock %}

templates/invitations/change_template.html
{% extends 'invitations/home.html' %}

{% block title %}<title>Change a template </title>{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST" action="/templates/change/{{ form.instance.id }}" class="form-group">
        {% csrf_token %}
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                {{form|crispy}}
            </div>
            <button type="submit" name="save" class="btn btn-success"> Save changes</button>
        </div>
    </form>
{% endblock %}

templates/invitations/create_groups.html
{% extends 'invitations/home.html' %}

{% block title %}<title>Creating a new group</title>{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Groups</h1>
    <p>Here you can add a group</p>
    <form method="POST" action="groups/create_groups/">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" name="save"> Create a new group</button>
    </form>
{% endblock %}

templates/invitations/events.html
{% extends 'invitations/home.html' %}
{% block title %}<title>Events</title>{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Events</h1>
    <form action="/events/add">
        <button type="submit" class="btn btn-success">Add an event</button>
    </form>


    {% if events %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Event</th>
                <th scope="col">Group</th>
                <th scope="col">Template</th>
                <th scope="col">Host</th>
                <th scope="col">Date</th>
                <th scope="col"> Print out all invitations</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for event in events %}

                <tr>
                    <td>{{ event.name }}</td>
                    <td>
                        <a href="/groups/view_group/{{ event.group.id }}">{{ event.group.name }}({{ event.group.guest_set.all.count }})</a>
                    </td>
                    <td>{{ event.template }}</td>
                    <td>{{ event.host }}</td>
                    <td>{{ event.date }}</td>
                    <td>
                        <form action="/events/render/{{ event.id }}" method="post" target="_blank">
                            {% csrf_token %}
                            {% if  event.group.guest_set.all.count %}
                                <button type="submit" class="btn btn-success">render</button>
                            {% else %}
                                <button type="submit" class="btn btn-success" disabled>render</button>
                            {% endif %}
                        </form>
                    </td>
                    <td>
                        <a href="/events/change/{{ event.id }}" class="btn btn-warning">change</a>
                    </td>

                    </td>
                    <td>
                        <form action="/events/delete/" method="post">
                            {% csrf_token %}
                            <input type="text" name="id" id="event_{{ event.id }}"
                                   value="{{ event.id }}" hidden>
                            <button type="submit" class="btn btn-danger">delete</button>

                        </form>
                    </td>
                </tr>
                </tbody>
            {% endfor %}
        </table>
    {% else %}
        <dev><p> You have no events yet </p></dev>
    {% endif %}
{% endblock %}

templates/invitations/groups.html
{% extends 'invitations/home.html' %}
{% block title %}<title>Groups</title>{% endblock %}

{% block content %}

    <h2>Friends</h2>

    <form action="/groups/add" method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
        <input type="text" name="name">
        <div class="input-group-prepend">
            <button type="submit" name="save" class="btn btn-success">Add a group</button>
        </div>
    </div>
    </form>

    {% if groups %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Group</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for group in groups %}
                <tr>
                    <td><a href="/groups/view_group/{{ group.id }}">{{ group.name }}({{ group.guest_set.all.count }})</a></td>
                    <td>
                        <form action="/groups/delete/" method="post">
                            {% csrf_token %}
                            <input type="text" name="id" id="group_{{ group.id }}"
                                   value="{{ group.id }}" hidden>
                            <button type="submit" class="btn btn-danger">delete</button>
                        </form>
                    </td>
                </tr>
                </tbody>
            {% endfor %}
        </table>
    {% else %}
        <dev><p> You have no groups </p></dev>
    {% endif %}



{% endblock %}

templates/invitations/guests.html
{% extends 'invitations/home.html' %}
{% block title %}<title>Guests</title>{% endblock %}
{% block content %}

    <h1>Friends</h1>
    <form action="/guests/add">
        <button type="submit" class="btn btn-success">Add a new guest</button>
    </form>

    <form method="POST" action="#">
    {% csrf_token %}
    {% if groups %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Group</th>
                <th scope="col">Guest, first name</th>
                <th scope="col">Guest, last name</th>
                <th scope="col">Guest, parent</th>
                <th scope="col">Guest, parent phone</th>
                <th scope="col"> </th>
                <th scope="col"> </th>
            </tr>
            </thead>
            <tbody>
            {% for group in groups %}
                {% for guest in  group.guest_set.all %}
                    <tr>
                        <td><a href="/groups/view_group/{{ group.id }}">{{ group.name }}</a></td>
                        <td>{{ guest.first_name}}</td>
                        <td>{{ guest.last_name }}</td>
                        <td>{{ guest.parent_name}}</td>
                        <td>{{ guest.parent_phone }}</td>
                        <td>
                            <a href="/guests/change/{{ guest.id }}" class="btn btn-warning">change guest</a>
                        </td>
                        <td>
                            <form action="/guests/delete/" method="post">
                                {% csrf_token %}
                                <input type="text" name="id" id="guest_{{ guest.id }}"
                                       value="{{ guest.id }}" hidden>
                                <button type="submit" class="btn btn-danger">delete guest</button>
                            </form>
                        </td>
                    </tr>
                    </tbody>
                {% endfor %}
            {% endfor %}
        </table>
    {% else %}
        <dev><p> You have no groups </p></dev>
    {% endif %}

{% endblock %}

templates/invitations/home.html
{% extends 'invitations/base.html' %}

{% block content %}
    <h3>Create Page</h3>
     <form method="get" action="/events/add/" class="form-group">
         {% csrf_token %}
         <div class="input-group mb-3">
             <div class="input-group-prepend">
                 <button type="submit" name="save" class="btn btn-success">Create new event</button>
             </div>{{form.name}}
         </div>
    </form>
{% endblock %}